server:
  port: 8100
spring:
  application:
    name: split-wise
  datasource:
    url: jdbc:mysql://localhost:3306/split_wise
    username: root
    password: 17151212@sK
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect

